export const mockCategories = [
  { id: 1, name: 'Keramik' },
  { id: 2, name: 'Kläder' },
  { id: 3, name: 'Smycken' },
  { id: 4, name: 'Accessoarer' },
  { id: 5, name: 'Servering/dukning' },
  { id: 6, name: 'Originalkonst' },
  { id: 7, name: 'Textilt' },
  { id: 8, name: 'Kort/klistermärken' },
  { id: 9, name: 'Posters' },
  { id: 10, name: 'Barn & Baby' },
  { id: 11, name: 'Belysning' },
];

export const realCreator = [
  {
    user_id: '6f1c0af5-f78f-4642-a0e1-687c08d99df9',
    created_at: '2025-06-18T12:38:51.573704+00:00',
    first_name: 'FörstaNamn',
    last_name: 'AndraNamn',
    role: 'test1',
    company_name: 'Test1',
    city: 'Test1',
    smsk_creator_categories: [
      {
        category_id: 1,
        smsk_categories: {
          name: 'Keramik',
        },
      },
    ],
    smsk_creator_styles: [],
    smsk_creator_materials: [
      {
        material_id: 12,
      },
    ],
    smsk_creator_features: [],
    imageUrls: [
      '/images/skaperian/bowls.jpg',
      '/images/skaperian/bowls2.jpg',
      '/images/skaperian/bowls.jpg',
      '/images/skaperian/bowls2.jpg',
    ],
  },
];

export const mockCreators = [
  {
    id: '1',
    displayName: 'Kreativa Krukan',
    first_name: 'Emma',
    last_name: 'Johansson',
    city: 'Lund',
    mainCategory: ['Keramik'],
    subcategories: ['Drejning', 'Väggdekorationer'],
    styles: ['Rustik', 'Organisk'],
    features: [
      'Har webbshop',
      'Erbjuder workshop',
      'Tar specialbeställningar',
      'Har showroom',
    ],
    imageUrls: [
      '/images/skaperian/bowls.jpg',
      '/images/skaperian/bowls2.jpg',
      '/images/skaperian/bowls.jpg',
      '/images/skaperian/bowls2.jpg',
    ],
    isFeatured: true,
  },
  {
    id: '2',
    displayName: 'Silversmeden',
    fullName: 'Marcus Eklund',
    city: 'Västerås',
    mainCategory: ['Smycken'],
    subcategories: ['Silver', 'Guld', 'Emalj'],
    styles: ['Modern', 'Elegant'],
    features: [
      'Har webbshop',
      'Erbjuder workshop',
      'Tar specialbeställningar',
      'Har showroom',
    ],
    imageUrls: [
      '/images/skaperian/bowls.jpg',
      '/images/skaperian/bowls2.jpg',
    ],
    isFeatured: false,
  },
  {
    id: '3',
    displayName: 'Tårtstudion',
    fullName: 'Sara Nyström',
    city: 'Karlstad',
    mainCategory: ['Bakverk'],
    subcategories: ['Tårtor', 'Cupcakes'],
    styles: ['Söt', 'Romantisk'],
    features: [
      'Har webbshop',
      'Erbjuder workshop',
      'Tar specialbeställningar',
      'Har showroom',
    ],
    imageUrls: [
      '/images/skaperian/bowls.jpg',
      '/images/skaperian/bowls2.jpg',
    ],
    isFeatured: false,
  },
  {
    id: '4',
    displayName: 'Glasglädje',
    fullName: 'Oskar Lindgren',
    city: 'Örebro',
    mainCategory: ['Glaskonst'],
    subcategories: ['Fusing', 'Blåst glas'],
    styles: ['Futuristisk', 'Färgglad'],
    features: [
      'Har webbshop',
      'Erbjuder workshop',
      'Tar specialbeställningar',
      'Har showroom',
    ],
    imageUrls: [
      '/images/skaperian/bowls.jpg',
      '/images/skaperian/bowls2.jpg',
    ],
    isFeatured: true,
  },
  {
    id: '5',
    displayName: 'Textilverk',
    fullName: 'Jenny Olsson',
    city: 'Norrköping',
    mainCategory: ['Textil'],
    subcategories: ['Tryck', 'Vävning'],
    styles: ['Naturnära', 'Geometrisk'],
    features: [
      'Har webbshop',
      'Erbjuder workshop',
      'Tar specialbeställningar',
      'Har showroom',
    ],
    imageUrls: [
      '/images/skaperian/bowls.jpg',
      '/images/skaperian/bowls2.jpg',
    ],
    isFeatured: false,
  },
  {
    id: '6',
    displayName: 'Lera & Liv',
    fullName: 'Henrik Sandström',
    city: 'Helsingborg',
    mainCategory: ['Keramik'],
    subcategories: ['Skulptur', 'Drejning'],
    styles: ['Rå', 'Experimentell'],
    features: [
      'Har webbshop',
      'Erbjuder workshop',
      'Tar specialbeställningar',
      'Har showroom',
    ],
    imageUrls: [
      '/images/skaperian/bowls.jpg',
      '/images/skaperian/bowls2.jpg',
    ],
    isFeatured: false,
  },
  {
    id: '7',
    displayName: 'Metallform',
    fullName: 'Isabelle Karlsson',
    city: 'Sundsvall',
    mainCategory: ['Metall'],
    subcategories: ['Skulptur', 'Bruksföremål'],
    styles: ['Industriell', 'Minimalistisk'],
    features: [
      'Har webbshop',
      'Erbjuder workshop',
      'Tar specialbeställningar',
      'Har showroom',
    ],
    imageUrls: [
      '/images/skaperian/bowls.jpg',
      '/images/skaperian/bowls2.jpg',
    ],
    isFeatured: false,
  },
  {
    id: '8',
    displayName: 'Målarboden',
    fullName: 'Karin Wallin',
    city: 'Kalmar',
    mainCategory: ['Måleri'],
    subcategories: ['Akryl', 'Akvarell'],
    styles: ['Abstrakt', 'Stämningsfull'],
    features: [
      'Har webbshop',
      'Erbjuder workshop',
      'Tar specialbeställningar',
      'Har showroom',
    ],
    imageUrls: [
      '/images/skaperian/bowls.jpg',
      '/images/skaperian/bowls2.jpg',
    ],
    isFeatured: true,
  },
  {
    id: '9',
    displayName: 'Form & Färg',
    fullName: 'Daniel Pettersson',
    city: 'Malmö',
    mainCategory: ['Illustration'],
    subcategories: ['Digitalt', 'Blyerts'],
    styles: ['Lekfull', 'Serieinspirerad'],
    features: [
      'Har webbshop',
      'Erbjuder workshop',
      'Tar specialbeställningar',
      'Har showroom',
    ],
    imageUrls: [
      '/images/skaperian/bowls.jpg',
      '/images/skaperian/bowls2.jpg',
    ],
    isFeatured: false,
  },
  {
    id: '10',
    displayName: 'Träverkstan',
    fullName: 'Moa Håkansson',
    city: 'Visby',
    mainCategory: ['Trä'],
    subcategories: ['Snickeri', 'Träsnideri'],
    styles: ['Traditionell', 'Robust'],
    features: [
      'Har webbshop',
      'Erbjuder workshop',
      'Tar specialbeställningar',
      'Har showroom',
    ],
    imageUrls: [
      '/images/skaperian/bowls.jpg',
      '/images/skaperian/bowls2.jpg',
    ],
    isFeatured: false,
  },
];
