import './globals.css';

import { Geist, Geist_Mono } from 'next/font/google';

import AuthWrapper from './components/AuthWrapper';
import HeaderWrapper from './components/headerWrapper';
import AppProvider from './context/appProvider';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable} ${geistMono.variable}
           antialiased flex flex-col h-screen w-screen overflow-hidden`}
      >
        <AppProvider>
          <AuthWrapper>
            <HeaderWrapper />
            <main className="flex-1 overflow-y-auto">
              {children}
            </main>
          </AuthWrapper>
        </AppProvider>
      </body>
    </html>
  );
}
